baseURL = "https://rumn2049.github.io/"
title = "Rumn's Blog"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo.386-master"
buildFuture = true

[params]
    mainpagetitle = "Rumn's Blog"
    mainpagesubtitle = """ "Coming 2 U live!" """
    mainpagedesc = " Welcome to Rumn's blog. Check the links below to access the posts."
    copyrightname = "Rumn"
    copyrighturl = ""
    showhugo = true
    github = "https://github.com/RUMN2049"
    bilibili = ""
    loadfastload = false
    loadspeedfactor = 1.0
    loadonepass = false

[params.copyright]
    name = "Rumn"
    url = ""
    prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"
    suffix = "Rumn's Blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"
    weight = 20

  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 30

[taxonomies]
categories = "categories"
tags = "tags"
series = "series"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.x]
    disableInlineCSS = true